apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: hono-kafka-cluster
spec:
  kafka:
    replicas: 1
    version: 2.1.0
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.1"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
